-- MySQL Script generated by MySQL Workbench
-- Wed Jun 14 22:57:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema netsales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema netsales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netsales` DEFAULT CHARACTER SET utf8 ;
USE `netsales` ;

-- -----------------------------------------------------
-- Table `netsales`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netsales`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(3,2) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `disponible` TINYINT NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsales`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netsales`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cliente` VARCHAR(45) NOT NULL,
  `total` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsales`.`DetalleVentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netsales`.`DetalleVentas` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `precio_unit` DECIMAL(5,2) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  PRIMARY KEY (`idDetalle`, `Producto_idProducto`, `Venta_idVenta`),
  INDEX `fk_DetalleVentas_Producto_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_DetalleVentas_Venta1_idx` (`Venta_idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_DetalleVentas_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `netsales`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleVentas_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `netsales`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsales`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `netsales`.`Trabajador` (
  `idTrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `contrasenia` VARCHAR(8) NOT NULL,
  `usuario` VARCHAR(12) NOT NULL,
  `activo` TINYINT NOT NULL,
  `sueldo` FLOAT NOT NULL,
  `comision` INT NOT NULL,
  PRIMARY KEY (`idTrabajador`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
