/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_1;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


public class panelVenderProducto extends javax.swing.JFrame {

    private int code;
    public static boolean bandera=false;
    public static fomularioVentas y;
    public static List<Integer>cantidades;//varible que trabaja a la par con Carrito,almacena las cantidades solicitadas
    public static List<Integer>carrito;//vaiable para almacenar el codigo de cada producto
    public static Admin admin=new Admin();
    private static final int i= ingreso.index;
    public panelVenderProducto() {
        initComponents();
        cantidades=new ArrayList<Integer>();
        carrito=new ArrayList<Integer>();
        this.botonContinuar.setVisible(false);
         this.setLocationRelativeTo(null);
        this.cajaCantidadDeProductos.setEnabled(false);
        this.mostrarProducto.setVisible(false);
        this.botonAñadirAlCarrito.setEnabled(false);
        this.textoEmergente.setVisible(false);
        this.cajaCodigo.setEnabled(false);
        this.cajaCodigo.setText("");;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        CajaBuscador = new javax.swing.JTextField();
        botonBuscador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textoEmergente = new javax.swing.JLabel();
        panelProductoEncontrado = new javax.swing.JPanel();
        botonAñadirAlCarrito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarProducto = new javax.swing.JTextArea();
        cajaCantidadDeProductos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cajaCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonDescuento = new javax.swing.JButton();
        botonRetroceder = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("*Venta*");

        CajaBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaBuscadorActionPerformed(evt);
            }
        });

        botonBuscador.setText("Buscar");
        botonBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscadorMouseClicked(evt);
            }
        });
        botonBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese codigo de producto");

        panelProductoEncontrado.setBackground(new java.awt.Color(204, 204, 204));

        botonAñadirAlCarrito.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonAñadirAlCarrito.setText("Ingresar Producto");
        botonAñadirAlCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAñadirAlCarritoMouseClicked(evt);
            }
        });
        botonAñadirAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirAlCarritoActionPerformed(evt);
            }
        });
        botonAñadirAlCarrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonAñadirAlCarritoKeyPressed(evt);
            }
        });

        mostrarProducto.setEditable(false);
        mostrarProducto.setBackground(new java.awt.Color(204, 204, 204));
        mostrarProducto.setColumns(20);
        mostrarProducto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mostrarProducto.setRows(5);
        jScrollPane1.setViewportView(mostrarProducto);

        cajaCantidadDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCantidadDeProductosActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad");

        jLabel3.setText("CODIGO DE DESCUENTO");

        botonDescuento.setText("OK.");
        botonDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDescuentoMouseClicked(evt);
            }
        });
        botonDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDescuentoActionPerformed(evt);
            }
        });
        botonDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonDescuentoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelProductoEncontradoLayout = new javax.swing.GroupLayout(panelProductoEncontrado);
        panelProductoEncontrado.setLayout(panelProductoEncontradoLayout);
        panelProductoEncontradoLayout.setHorizontalGroup(
            panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoEncontradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoEncontradoLayout.createSequentialGroup()
                        .addGroup(panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cajaCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductoEncontradoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajaCantidadDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProductoEncontradoLayout.createSequentialGroup()
                                .addComponent(botonDescuento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAñadirAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(panelProductoEncontradoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelProductoEncontradoLayout.setVerticalGroup(
            panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoEncontradoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cajaCantidadDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAñadirAlCarrito)
                    .addGroup(panelProductoEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cajaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonDescuento)))
                .addContainerGap())
        );

        botonRetroceder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonRetroceder.setText("Atras");
        botonRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetrocederActionPerformed(evt);
            }
        });

        botonContinuar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonContinuar.setText("Continuar");
        botonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonContinuarMouseClicked(evt);
            }
        });
        botonContinuar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonContinuarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(botonBuscador)
                        .addGap(35, 35, 35)
                        .addComponent(CajaBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(textoEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(293, 293, 293)
                                .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelProductoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscador)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(CajaBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textoEmergente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(panelProductoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRetroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaBuscadorActionPerformed

    private void botonBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscadorMouseClicked
           try {
               //se realiza la busqueda secuencial a travez de la funcion de Vendedores: BuscarProducto
        code=Integer.parseInt(CajaBuscador.getText());
        code=admin.getVendedores().get(i).buscarProducto(code); String text="";
        this.textoEmergente.setVisible(true);
        if(code==-1){
              this.textoEmergente.setText("Producto no encontrado");//si no lo encuentra mandara un mensaje en el panel
              this.mostrarProducto.setText("");
              this.cajaCantidadDeProductos.setEnabled(false);
              this.botonAñadirAlCarrito.setEnabled(false);
        }else{
        this.textoEmergente.setText("Producto Encontrado");//si encuentra el producto entonces el panel y el area de texto mostraran los datos
        this.botonAñadirAlCarrito.setEnabled(true);
        this.cajaCantidadDeProductos.setEnabled(true);
        this.mostrarProducto.setEnabled(true);
        this.mostrarProducto.setVisible(true);
        this.cajaCodigo.setEnabled(true);
        text+="Producto:\t"+admin.getVendedores().get(i).getListaProducto().get(code).getDescipcion()+"\n";
        text+="Precio:  \t"+"S/.*"+admin.getVendedores().get(i).getListaProducto().get(code).getPrecio()+"\n";
        text+="Cantidad:\t"+admin.getVendedores().get(i).getListaProducto().get(code).getCantidad()+"\n";
        this.mostrarProducto.setText(text);
        }
        } catch (Exception e) {
             e.printStackTrace(); JOptionPane.showMessageDialog(null,"ERROR:"+e.toString()+"\nRellenar Correctamente los campos");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscadorMouseClicked
    
    private void cajaCantidadDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCantidadDeProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCantidadDeProductosActionPerformed

    private void botonRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetrocederActionPerformed
        // TODO add your handling code here:
        panelVentas a=new panelVentas();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRetrocederActionPerformed

    private void botonAñadirAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirAlCarritoActionPerformed
       
        
    }//GEN-LAST:event_botonAñadirAlCarritoActionPerformed

    private void botonBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscadorActionPerformed

    }//GEN-LAST:event_botonBuscadorActionPerformed

    private void botonAñadirAlCarritoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonAñadirAlCarritoKeyPressed
    
    }//GEN-LAST:event_botonAñadirAlCarritoKeyPressed

    private void botonContinuarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonContinuarKeyPressed
 
    }//GEN-LAST:event_botonContinuarKeyPressed

    private void botonContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonContinuarMouseClicked
        y=new fomularioVentas();
        y.setVisible(true);
    }//GEN-LAST:event_botonContinuarMouseClicked

    private void botonAñadirAlCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAñadirAlCarritoMouseClicked
         try {        
             //este boton añade el indice del producto al carrito con sus cantidades
         int cant=Integer.parseInt(cajaCantidadDeProductos.getText());
        if((cant>admin.getVendedores().get(i).getListaProducto().get(code).getCantidad())&&cant>=25){
        JOptionPane.showMessageDialog(null,"La cantidad ingresada excede el limite");
        }
        if(admin.getVendedores().get(i).getListaProducto().get(code).getCantidad()==0){
        JOptionPane.showMessageDialog(null,"No hay stock disponible\nConsutar a administrador");
        } 
        if(cant<=admin.getVendedores().get(i).getListaProducto().get(code).getCantidad()){
            carrito.add(code);
            this.botonContinuar.setVisible(true);
            JOptionPane.showMessageDialog(null,"Producto Ingresado al carrito");//si las cantidades estan dentro del rango, seran almacenados al carrito
            cantidades.add(cant);
        }
        } catch (Exception e) {
            e.printStackTrace(); JOptionPane.showMessageDialog(null,"ERROR:"+e.toString()+"\nRellenar Correctamente los campos");
        }
    }//GEN-LAST:event_botonAñadirAlCarritoMouseClicked

    private void botonDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDescuentoActionPerformed

    private void botonDescuentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonDescuentoKeyPressed
        
    }//GEN-LAST:event_botonDescuentoKeyPressed

    private void botonDescuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDescuentoMouseClicked
    //este boton evalua el codigo de decuento a travez de la funcion CodeOffSale, el retorno devolvera un valor booleano, si es verdadero sera canjeado
        if(this.cajaCodigo.getText()!=""){
            if(admin.getVendedores().get(i).codeOffSale(this.cajaCodigo.getText())){
            bandera=true;
            JOptionPane.showMessageDialog(null,"Codigo Canjeado");this.botonDescuento.setVisible(false);
            }else JOptionPane.showMessageDialog(null,"Codigo No valido");
        }else JOptionPane.showMessageDialog(null,"Codigo No valido");
    }//GEN-LAST:event_botonDescuentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelVenderProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelVenderProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelVenderProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelVenderProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelVenderProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaBuscador;
    private javax.swing.JButton botonAñadirAlCarrito;
    private javax.swing.JButton botonBuscador;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonDescuento;
    private javax.swing.JButton botonRetroceder;
    private javax.swing.JTextField cajaCantidadDeProductos;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mostrarProducto;
    private javax.swing.JPanel panelProductoEncontrado;
    private javax.swing.JLabel textoEmergente;
    // End of variables declaration//GEN-END:variables
}
